/*
 * This source file was generated by the Gradle 'init' task
 */
package com.melon.pixelize;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SimpleTest {
    @Test void appHasAGreeting() {
        assertTrue( true );
    }
}
